### ISSUE TITLE
Mapio: fichier de sauvegarde

### ISSUE THREAD

**Issue by tlanvaldear** [tlanvaldear/MLP-simulator#1]
D'après le commit sur README de `mperroy` :

>Pour que l'on soit tous d'accord sur la sauvegarde (et le chargement) des maps:
> Ce qui me semble bien : (fichier type) 
> -Largeur 
> -Hauteur 
> -Nombre d'objets différents sur la map 
> -Matrice d'entier = contenu de chaque case de la map (exemple) `0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1` 
> -Type d'objet NomFichierImage NbSprites Propriétés(type 1) NomFichierImage NBSprites Propriétés(type 2) ...(pour tous les types présents)

Cet usage a l'air pas mal, mais

En ce qui concerne la matrice d'entier, pourquoi ne pas définir un type énuméré pouvant user des maps pour leur donner un index, afin que le fichier aie une matrice des objets de la map avec directement de quel objet il s'agit ?
un truc du genre :
```
-1  -1  -1  -1  -1  -1  -1  -1  -1 
-1   5  -1   5  -1   5  -1   5  -1
 5  -1   5  -1   5  -1   5   -1  5
-1   5   -1  5  -1   5   -1   5  -1
```
nous ferait du coup obtenir une map sans bordure (`5` étant `pas d'objet`) avec à la place des `5` des pièces, puisque c'est le sixième objet défini dans mapio.c

**Comment by mperroy** [comment]
Pour la matrice d'objet, il y a déjà des entiers pour les objets.
Exemple : il y a 0 pour le sol et 1 pour les murs, donc je pense qu'il y a déjà des entiers attitrés.
Mais je vérifierai pour tous les objets pour en être certain.
(Et oui c'est mieux que le README, mais c'est pour être certain que tous le monde puisse le voir)

**Comment by GLamarque** [comment]
Vous inquiétez pas si je suis en mode sourdine ces jours-ci, je suis en train de bosser le projet de réseau, mais dans deux ou trois jours, je switcherais sur le projet de ProgSys, don't worry! ;)

**Comment by mperroy** [comment]
Sa marche Gautier ;)

**Comment by mperroy** [comment]
Du coup j'ai regardé pour les valeurs d'entiers pour la matrice est donc :
0 = bloc du sol (solide)
1 = bloc des murs (solide)
2 = bloc eponge/mousse (jaune) (semi-solide)
3 = bloc blanc (destructible)
4 = fleur
5 = pièces

**Comment by tlanvaldear** [comment]
Ok, il manque plus qu'à mettre les cases vides c'est à dire celles qui n'ont aucun objet, deux choix : -1 ou 6

**Comment by mperroy** [comment]
En fait, la fonction s'en occupe déjà et retourne -1 lorsqu'il n'y a pas d'objet.

**Comment by tlanvaldear** [comment]
ça marche alors !
Je m'y mets dès ce week end pour réseau & PRS, là j'suis un peu bloqué avec le projet techno :|
