### ISSUE TITLE
Map_save

### ISSUE THREAD

**Issue by mperroy** [tlanvaldear/MLP-simulator#2]
Pour la fonction map_save, je l'ai quasiment terminé mais je me bat avec un seg fault (pour changer).

**Comment by tlanvaldear** [comment]
Si besoin, tu peux créer une branch et commit même si ça marche pas, qu'on puisse y jeter un oeil !
Au cas où : 
`git branch nombranch`
`git checkout nombranch`
puis tu peux commit as usual, en faisant attention à 
`git push origin nombranch` plutôt qu'`origin master`

**Comment by mperroy** [comment]
Ok problème résolu !!!
Si vous y jettez un oeil, j'ai mis l'entier correspondant au vide donc le tableau des types mais je pense que l'enlever c'est mieux, ditez moi si vous êtes d'accord.
Et si vous avez des questions dessus, allez y !
