### ISSUE TITLE
Map_load

### ISSUE THREAD

**Issue by mperroy** [tlanvaldear/MLP-simulator#3]
J'ai push dans une autre branche, la fonction map_load mais qui n'est pas fonctionnel (erreur de seg).
Je vais essayer de régler ça demain.

**Comment by mperroy** [comment]
Y a plusieurs soucis : La récupération du chemin du fichier de l'objet
Et le troisième paramètre de la fonction map_object_add, qui est un unsigned (ce que j'ai push est une mauvaise solution, c'est très bête).
Du coup j'attend votre petit coup de main dessus, je me suis possiblement compliqué la tâche pour rien.

**Comment by tlanvaldear** [comment]
Ligne 170: 

```C
for(int i = 0; i < strlen(fillPathPngFile); i++) {
      if(!(fillPathPngFile[i] == '0'))
        pathPngFile += fillPathPngFile[i];
    }
``` 
il semble y avoir un segfault à cause de ton `strlen` sur `fillPathPngFile`. Mais cette ligne :
```C
pathPngFile += fillPathPngFile[i];
```
la concaténation marche pas comme ça en C, ça aurait créé aussi une belle segfault
Je vais bosser dessus

**Comment by tlanvaldear** [comment]
J'aurai besoin d'éclaircissement du coup sur cette partie, parce que j'arrive pas à exactement comprendre où tu voulais aller avec ça

**Comment by tlanvaldear** [comment]
Il va me falloir des précisions sur ce qui se passe aux alentours de fillPathPngFile

Je vais essayer demain (parce que là j'ai un visuel a retaper et un rapport a faire pour le pt) de recoder l'intégralité de `load` en me basant sur `save`

**Comment by GLamarque** [comment]
J'ai tout refait, ça fonctionne ;) Je close.
