### ISSUE TITLE
choix de session

### ISSUE THREAD

**Issue by tlanvaldear** [tlanvaldear/MLP-simulator#6]
Le doodle est prêt sur les news, il faudrait se mettre d'accord sur l'une des quatre sessions possibles !

**Comment by mperroy** [comment]
On a cours que mardi aprem sinon c'est libre
Et pour rappel la deadline de ce projet est demain (vendredi 6 janvier) à 12h00
(Et il faut faire un rapport)

**Comment by GLamarque** [comment]
Vu que j'ai fait la plupart du code, je vais faire le rapport demain matin et je m'occupe d'envoyer l'archive avant midi.

**Comment by GLamarque** [comment]
Comment on accède au Doodle?

**Comment by tlanvaldear** [comment]
http://doodle.com/poll/x54eruunew2xi8uw

**Comment by GLamarque** [comment]
Thank you :)

**Comment by GLamarque** [comment]
Ça vous va mercredi pour la soutenance?

**Comment by tlanvaldear** [comment]
Pas de souci !

**Comment by GLamarque** [comment]
OK, on est inscrit à la session numéro 3 pour mercredi.
