### ISSUE TITLE
Temporisateur

### ISSUE THREAD

**Issue by mperroy** [tlanvaldear/MLP-simulator#7]
Je dois avouer que je sèche un peu dessus :(

**Comment by tlanvaldear** [comment]
je suis en train de le faire 
j'ai fait la structure itimerval et l'appel a setitimer dans timer_set
je suis en train de vérifier comment stocker param, puisqu'une volatile void* ne suffit pas a le stocker

**Comment by tlanvaldear** [comment]
Soit param = nil, soit j'arrive pas a le stocker... le fait que param soit un void* dérange beaucoup parce que du coup je sais pas quoi y mettre comme sizeof pour un memcpy

**Comment by tlanvaldear** [comment]
Ok, le "départ" suffit amplement, il suffisait de retirer `alarm(2)` dans le demon() pour que ça fonctionne correctement sans "nil" ! (remplacé par `timer_set(200,"oui")` pour tester)

**Comment by tlanvaldear** [comment]
Je vais avoir besoin d'un coup de main pour l'implémentation totale !
(Déjà parce que l'énoncé est pas facile à suivre, puis parce que si je lance le jeu avec les timers actifs, timer_set ne s'appelle que si je ferme le jeu (?!))
