### ISSUE TITLE
Maputil.c

### ISSUE THREAD

**Issue by mperroy** [tlanvaldear/MLP-simulator#8]
int new_type = 0;
        for (int i = 0; i < nb_objects; ++i) {
            if (is_used[i]){
                for (int y = 0; y < height; ++y) {
                    for (int x = 0; x < width; ++x) {
                        if (matrix[x][y] == i){
                            matrix[x][y] = new_type;
                        }
                    }
                }
                new_type++;
            }
        }

Je ne vois pas à quoi sert ce bout de code, c'est pour --pruneobjets.
Dsl pour le copier-coller dégueu, sinon c'est les lignes 543 à 555 dans le fichier(maputil.c)

**Comment by tlanvaldear** [comment]
```C
        int new_type = 0;
        for (int i = 0; i < nb_objects; ++i) {
            if (is_used[i]){
                for (int y = 0; y < height; ++y) {
                    for (int x = 0; x < width; ++x) {
                        if (matrix[x][y] == i){
                            matrix[x][y] = new_type;
                        }
                    }
                }
                new_type++;
            }
        }
```

D'après ce que j'en comprends, on cherche les objets dans la matrice qui correspondent aux occurrences de chaque objet utilisé sur la carte.

Pour plus tard, en MD, tu peux te permettre d'user des balises ` ```C  CODE_ICI ``` ` pour les laisser avec la coloration du C et l'indentation

**Comment by mperroy** [comment]
Ok ok mais du coup je ne comprend son utilité pour cette option de la commande (suppression des objets sans occurrence sur la carte)

**Comment by GLamarque** [comment]
En fait, si t'as que les objets 0, 4 et 8 dans la matrice par exemple, ça va les transformer en 0, 1 et 2.
