### ISSUE TITLE
Rapport

### ISSUE THREAD

**Issue by mperroy** [tlanvaldear/MLP-simulator#9]
Vous avez une présence comme support pour le rapport, du genre un truc en partagé comme goodle drive pour que l'on bosse en même temps ?

**Comment by tlanvaldear** [comment]
Quote
```
GLamarque commented 2 hours ago
Vu que j'ai fait la plupart du code, je vais faire le rapport demain matin et je m'occupe d'envoyer l'archive avant midi.
```
Mais, on peut utiliser overleaf pour le rapport si vous voulez le faire en LaTeX

**Comment by GLamarque** [comment]
Ouais carrément c'est une bonne idée

**Comment by tlanvaldear** [comment]
https://www.overleaf.com/7641089tbtfhxytxjxn

**Comment by mperroy** [comment]
Ok ok, putain de coupure internet chez moi là, assez embétant, du coup si tu as besoin d'aide ou des précisions pour le rapport, je serais là

**Comment by tlanvaldear** [comment]
J'ai fait le plan, je vais commencer à rédiger ce dont je pense être sûr de savoir
Faudrait faire la même en réseau

**Comment by GLamarque** [comment]
Pour ma part, j'ai fait toutes les modifications que je pouvais faire sur le rapport.
Qui l'envoie?

**Comment by tlanvaldear** [comment]
J'ai mis tous les bouts de code dans l'espace qui fait du color syntaxing, et pour moi ça sera bon
Si tout vous va, on devrait avoir de quoi le déposer, je suppose, et je peux faire ça

**Comment by GLamarque** [comment]
OK nous nous en remettons à toi Yoan, pour rendre le saint projet :D (Le color syntaxing c'est cool)

**Comment by mperroy** [comment]
J'ai fait mes modifications également tout est bon du coup.
Du coup je te laisse le faire yoan

**Comment by GLamarque** [comment]
Amen les amis!

**Comment by mperroy** [comment]
Et comme on dit gg les mecs pour le projet xD
(Maintenant go faire le rapport de réseau pour nous)

**Comment by GLamarque** [comment]
J'ai essayé de blablater pour les temporisateurs xD je sens bien que wacrenier va nous défoncer

**Comment by mperroy** [comment]
On va pas être les seul je pense, mais ouais ....

**Comment by tlanvaldear** [comment]
pour l'archive il me faut vos login (juste le login) pour que le prof sache d'où ça vient :
tar czf x-login1-login2-login3-CLEF-SECRETE.tar.gz rapport.pdf *.c

**Comment by mperroy** [comment]
matperroy pour ma part

**Comment by GLamarque** [comment]
Moi c'est glamarqu mon login au CREMI.

**Comment by tlanvaldear** [comment]
```
tar tzf /net/cremi/pwacreni/MARIO/3-glamarqu-matperroy-ymarty-12345a.tar.gz 
rapport.pdf
maputil.c
mapio.c
tempo.c
```
Déposé !

**Comment by mperroy** [comment]
Parfait !

**Comment by GLamarque** [comment]
Nickel!

**Comment by tlanvaldear** [comment]
Pour ce qui est des sources j'ai dl ce qu'il y avait du dernier commit, ça devrait être bon normalement !
Plus qu'à finir le rapport de réseau, puis repos :<

**Comment by tlanvaldear** [comment]
En parlant de réseau, tiens : 
```Bonjour,

j'ai bien reçu votre projet.

Je ne sais pas si vous aurez le temps de changer ça,
mais il faut que tout votre projet tienne en un seul fichier .py ...

"
Sur le serveur, on lance le programme sans argument, et le programme
doit alors ouvrir une socket TCP en écoute. Sur les clients, on lance
le programme avec le nom du serveur en paramètre, le programme doit,
dans ce cas, se connecter en TCP à la machine passée en paramètre.
"
```
En gros, je le mets ici au cas où vous ayiez fait la même chose que nous au niveau du jeu c'est à dire deux modules exécutables, mais il faut apparemment que tout tienne en un seul fichier !

**Comment by GLamarque** [comment]
Nous on lance avec un seul programme mais on a séparé les codes dans deux fichiers donc ça devrait le faire

**Comment by tlanvaldear** [comment]
Oui !
